const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Element{constructor(){this.value='';this.checked=false;this.disabled=false;this.children=[];this.style={};this.dataset={};this.className='';this.classList={add:()=>{},remove:()=>{},toggle:()=>{}};}append(...args){this.children.push(...args)}replaceChildren(){this.children=[]}setAttribute(){}addEventListener(){}getBoundingClientRect(){return {width:800,height:520,left:0,top:0}}getContext(){return new Proxy({measureText:s=>({width:s.length*6})},{get:(o,k)=>o[k]||(()=>{})})}}
function boot(){const elements={};const get=id=>elements[id]||(elements[id]=new Element());Object.assign(get('shell'),{value:'open'});get('recipe').value='stir';get('salt').value='1';get('spice').value='0';get('speed').value='2';get('request').value='Bò xào hành tây, ít mặn, ít nước.';get('fault').value='none';get('coldOK').checked=get('potOK').checked=get('labels').checked=true;let raf;const sandbox={console,document:{getElementById:get,createElement:()=>new Element(),querySelectorAll:()=>[],querySelector:()=>get('progress-role')},window:{devicePixelRatio:1},localStorage:{getItem:()=>null,setItem:()=>{}},ResizeObserver:class{observe(){}},requestAnimationFrame:f=>raf=f};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/simulator.js','utf8'),sandbox);const run=s=>vm.runInContext(s,sandbox);return {get,run,tick:(seconds)=>{for(let t=0;t<seconds*20;t++)run('frame('+(t+1)*50+')')}}}
let t=boot();t.run('start()');t.tick(35);assert.equal(t.run('sim.state'),'complete');assert.equal(t.run('sim.usedCount'),4);assert.equal(t.run('trays[4].used'),false);assert.equal(t.run('sim.heat'),false);
t=boot();t.get('fault').value='jam';t.run('start()');t.tick(15);assert.equal(t.run('sim.state'),'error');assert.equal(t.run('trays[1].used'),false);assert.equal(t.run('sim.rpm'),0);
t=boot();t.get('fault').value='overheat';t.run('start()');t.tick(20);assert.equal(t.run('sim.state'),'error');assert.equal(t.run('sim.heat'),false);
t=boot();t.get('coldOK').checked=false;t.run('start()');assert.equal(t.run('sim.state'),'idle');assert.match(t.get('phase').textContent,/Chặn/);
t=boot();t.get('potOK').checked=false;t.run('start()');assert.equal(t.run('sim.state'),'idle');
t=boot();t.run('start()');t.tick(5);t.get('pause').onclick();assert.equal(t.run('sim.state'),'paused');assert.equal(t.run('sim.heat'),false);const count=t.run('sim.usedCount');t.get('pause').onclick();assert.equal(t.run('sim.usedCount'),count);t.get('stop').onclick();assert.equal(t.run('sim.state'),'stopped');t.get('reload').onclick();assert.equal(t.run('sim.state'),'idle');assert.equal(t.run('sim.usedCount'),0);
t=boot();t.get('request').value='Pizza nướng';assert.equal(t.run('plan()'),false);t.get('request').value='Canh thịt rau';t.get('recipe').value='soup';assert.equal(t.run('plan()'),true);t.run('start()');t.tick(40);assert.equal(t.run('sim.state'),'complete');assert.equal(t.run('sim.usedCount'),5);
t=boot();t.get('request').value='Thịt kho';t.get('recipe').value='braise';t.run('start()');t.tick(35);assert.equal(t.run('sim.state'),'complete');assert.equal(t.run('sim.usedCount'),2);t.get('rating').value='lessSalt';t.get('saveRating').onclick();assert.equal(t.run('prefs.braise'),'lessSalt');
console.log('PASS: completion, retained trays, jam, overheat, cold/pot interlocks, pause/resume, stop/reset, unsupported request, soup, braise, feedback.');
